apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}

  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        azure.workload.identity/use: "true" 
    spec:
      serviceAccountName: {{ .Values.appName }}-sa

      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.appName }}-kv

      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh", "-c", "sleep 3600"]

        ports:
        - containerPort: {{ .Values.service.port }}

        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets"
          readOnly: true

  strategy:
    blueGreen:
      activeService: {{ .Values.appName }}
      previewService: {{ .Values.appName }}-preview
      autoPromotionEnabled: false